### ISSUE TITLE
Why does make geojson/albers/state-bounds.json throw an error? 

### ISSUE THREAD

**Issue by emamd** [WPMedia/wapo-map-data#20]
```
❯ make geojson/albers/state-bounds.json                                                                         elections-2018 …
cat geojson/albers/states.geojson | ./extract-projected-bounds > geojson/albers/state-bounds.json
/Users/emamdjomeha/repos/wapo-map-data/node_modules/proj4/dist/proj4-src.js:1775
	    throw new TypeError('coordinates must be finite numbers');
	    ^

TypeError: coordinates must be finite numbers
    at checkCoord (/Users/emamdjomeha/repos/wapo-map-data/node_modules/proj4/dist/proj4-src.js:1775:12)
    at checkSanity (/Users/emamdjomeha/repos/wapo-map-data/node_modules/proj4/dist/proj4-src.js:1767:4)
    at transform (/Users/emamdjomeha/repos/wapo-map-data/node_modules/proj4/dist/proj4-src.js:1791:4)
    at transformer (/Users/emamdjomeha/repos/wapo-map-data/node_modules/proj4/dist/proj4-src.js:1863:25)
    at Object.forward (/Users/emamdjomeha/repos/wapo-map-data/node_modules/proj4/dist/proj4-src.js:1918:17)
    at DestroyableTransform.write [as _transform] (/Users/emamdjomeha/repos/wapo-map-data/extract-projected-bounds:25:17)
    at DestroyableTransform.Transform._read (/Users/emamdjomeha/repos/wapo-map-data/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/emamdjomeha/repos/wapo-map-data/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/emamdjomeha/repos/wapo-map-data/node_modules/readable-stream/lib/_stream_writable.js:418:64)
    at writeOrBuffer (/Users/emamdjomeha/repos/wapo-map-data/node_modules/readable-stream/lib/_stream_writable.js:407:5)
make: *** [geojson/albers/state-bounds.json] Error 1
```

**Comment by emamd** [comment]
`extract-projected-bounds.js` appears to originally have relied on a `bbox` propertyin the input geojson. For some reason, this does not appear to exist in the geojson we're producing. The function will have to be refactored to extract a bounding box based on the feature coordinates. 

https://github.com/WPMedia/wapo-map-data/blob/master/extract-projected-bounds#L21-L41

```
function write(feat, _, next) {
  var bbox = feat.bbox;
  var p1 = proj.forward([bbox[0], bbox[1]]);
  var p2 = proj.forward([bbox[2], bbox[3]]);

  bbox = [
    Math.min(p1[0], p2[0]),
    Math.min(p1[1], p2[1]),
    Math.max(p1[0], p2[0]),
    Math.max(p1[1], p2[1])
  ];

  nation = nation.map(function(memo, i) {
    return (i < 2 ? Math.min : Math.max)(memo, bbox[i]);
  });

  next(null, {
    id: feat.properties.id,
    bbox: bbox
  });
}
```

**Comment by emamd** [comment]
I think I hacked my way around this for now.
